-- =============================================================================
-- Snow Fashion 교육 환경 셋업 스크립트
-- 실행 순서: 이 스크립트 실행 → CSV 업로드 → 01_load_data.sql 실행
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Database
CREATE DATABASE IF NOT EXISTS SNOW_FASHION;

-- 2. Schemas
CREATE SCHEMA IF NOT EXISTS SNOW_FASHION.RAW       COMMENT = '원본 데이터';
CREATE SCHEMA IF NOT EXISTS SNOW_FASHION.ANALYTICS  COMMENT = '분석용 마트';
CREATE SCHEMA IF NOT EXISTS SNOW_FASHION.SEMANTIC   COMMENT = 'AI 오브젝트 (Semantic View, Agent, Search Service 등)';

-- 3. Warehouse
CREATE WAREHOUSE IF NOT EXISTS SF_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  COMMENT        = '스노우패션 교육용 웨어하우스';

USE WAREHOUSE SF_WH;
USE SCHEMA SNOW_FASHION.RAW;

-- =============================================================================
-- 4. Tables (12개)
-- =============================================================================

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.CUSTOMERS (
    CUSTOMER_ID       VARCHAR(15) NOT NULL,
    AGE_GROUP         VARCHAR(10) NOT NULL,
    GENDER            VARCHAR(5) NOT NULL,
    REGION            VARCHAR(20) NOT NULL,
    MEMBERSHIP_TIER   VARCHAR(10) DEFAULT 'BASIC',
    SIGNUP_DATE       DATE NOT NULL,
    SIGNUP_CHANNEL    VARCHAR(20) NOT NULL,
    TOTAL_PURCHASES   NUMBER(10,0) DEFAULT 0,
    IS_ACTIVE         BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.DEMAND_FORECAST (
    SERIES_ID     VARIANT,
    BRAND         VARCHAR(16777216),
    CATEGORY      VARCHAR(16777216),
    FORECAST_DATE DATE,
    FORECAST_QTY  FLOAT,
    LOWER_BOUND   FLOAT,
    UPPER_BOUND   FLOAT
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.INVENTORY_SNAPSHOT (
    SNAPSHOT_DATE  DATE NOT NULL,
    STORE_ID       VARCHAR(10) NOT NULL,
    SKU_ID         VARCHAR(20) NOT NULL,
    BRAND          VARCHAR(20) NOT NULL,
    ON_HAND_QTY    NUMBER(38,0) NOT NULL,
    IN_TRANSIT_QTY NUMBER(38,0) DEFAULT 0,
    RESERVED_QTY   NUMBER(38,0) DEFAULT 0,
    REORDER_POINT  NUMBER(38,0) DEFAULT 10,
    STATUS         VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.PRODUCTS (
    SKU_ID        VARCHAR(20) NOT NULL,
    BRAND         VARCHAR(20) NOT NULL,
    CATEGORY      VARCHAR(30) NOT NULL,
    SUB_CATEGORY  VARCHAR(30) NOT NULL,
    PRODUCT_NAME  VARCHAR(200) NOT NULL,
    SEASON        VARCHAR(10) NOT NULL,
    SEASON_YEAR   NUMBER(38,0) NOT NULL,
    COLOR         VARCHAR(20) NOT NULL,
    SIZE_GROUP    VARCHAR(10) NOT NULL,
    GENDER        VARCHAR(10) NOT NULL,
    COST_PRICE    NUMBER(10,0) NOT NULL,
    RETAIL_PRICE  NUMBER(10,0) NOT NULL,
    LAUNCH_DATE   DATE NOT NULL,
    IS_ACTIVE     BOOLEAN DEFAULT TRUE,
    CREATED_AT    TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SKU_ID)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.PRODUCT_REVIEWS (
    REVIEW_ID      VARCHAR(16777216),
    SKU_ID         VARCHAR(20),
    BRAND          VARCHAR(20),
    CUSTOMER_ID    VARCHAR(16777216),
    REVIEW_DATE    DATE,
    RATING         NUMBER(1,0),
    REVIEW_TEXT    VARCHAR(16777216),
    REVIEW_CHANNEL VARCHAR(4),
    HELPFUL_COUNT  NUMBER(2,0)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.REVIEW_TEMPLATES (
    ID          NUMBER(18,0),
    RATING      NUMBER(1,0),
    REVIEW_TEXT VARCHAR(16777216)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.SALES_TRANSACTIONS (
    TXN_ID          VARCHAR(20) NOT NULL,
    TXN_DATE        DATE NOT NULL,
    TXN_TIME        TIMESTAMP_NTZ(9) NOT NULL,
    CUSTOMER_ID     VARCHAR(15),
    STORE_ID        VARCHAR(10) NOT NULL,
    SKU_ID          VARCHAR(20) NOT NULL,
    BRAND           VARCHAR(20) NOT NULL,
    CHANNEL         VARCHAR(20) NOT NULL,
    QUANTITY         NUMBER(38,0) NOT NULL,
    UNIT_PRICE      NUMBER(10,0) NOT NULL,
    DISCOUNT_RATE   NUMBER(4,2) DEFAULT 0,
    SALE_AMOUNT     NUMBER(12,0) NOT NULL,
    PAYMENT_METHOD  VARCHAR(20) NOT NULL,
    PRIMARY KEY (TXN_ID)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.SHIPMENTS (
    SHIPMENT_ID  VARCHAR(15) NOT NULL,
    ORDER_ID     VARCHAR(15) NOT NULL,
    VENDOR_ID    VARCHAR(10) NOT NULL,
    SHIP_DATE    DATE,
    ARRIVAL_DATE DATE,
    SHIPPED_QTY  NUMBER(38,0),
    STATUS       VARCHAR(15) NOT NULL,
    DELAY_DAYS   NUMBER(38,0) DEFAULT 0,
    PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.STORES (
    STORE_ID    VARCHAR(10) NOT NULL,
    STORE_NAME  VARCHAR(100) NOT NULL,
    BRAND       VARCHAR(20) NOT NULL,
    STORE_TYPE  VARCHAR(20) NOT NULL,
    REGION      VARCHAR(20) NOT NULL,
    CITY        VARCHAR(30) NOT NULL,
    DISTRICT    VARCHAR(30),
    OPEN_DATE   DATE NOT NULL,
    AREA_SQM    NUMBER(6,1),
    IS_ACTIVE   BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (STORE_ID)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.SUPPLY_ORDERS (
    ORDER_ID          VARCHAR(15) NOT NULL,
    VENDOR_ID         VARCHAR(10) NOT NULL,
    SKU_ID            VARCHAR(20) NOT NULL,
    BRAND             VARCHAR(20) NOT NULL,
    ORDER_DATE        DATE NOT NULL,
    EXPECTED_DELIVERY DATE NOT NULL,
    ORDER_QTY         NUMBER(38,0) NOT NULL,
    UNIT_COST         NUMBER(10,0) NOT NULL,
    TOTAL_COST        NUMBER(12,0) NOT NULL,
    STATUS            VARCHAR(15) NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.VENDORS (
    VENDOR_ID      VARCHAR(10) NOT NULL,
    VENDOR_NAME    VARCHAR(100) NOT NULL,
    VENDOR_TYPE    VARCHAR(20) NOT NULL,
    COUNTRY        VARCHAR(20) NOT NULL,
    CITY           VARCHAR(30),
    LEAD_TIME_DAYS NUMBER(38,0) NOT NULL,
    QUALITY_SCORE  NUMBER(3,1),
    IS_ACTIVE      BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (VENDOR_ID)
);

CREATE TABLE IF NOT EXISTS SNOW_FASHION.RAW.WEEKLY_DEMAND (
    WEEK_DATE DATE,
    BRAND     VARCHAR(20),
    CATEGORY  VARCHAR(30),
    QUANTITY  NUMBER(38,0),
    SALES_MM  NUMBER(31,1)
);

-- =============================================================================
-- 셋업 완료 확인
-- =============================================================================
SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT
FROM SNOW_FASHION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW' AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;
