-- =============================================================================
-- Snow Fashion 데이터 로드 스크립트
-- 사전 조건: 00_setup_db.sql 실행 완료, data/ 폴더에 CSV.gz 파일 12개 준비
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SF_WH;
USE SCHEMA SNOW_FASHION.RAW;

-- =============================================================================
-- 1. File Format (gzip 압축 CSV용)
-- =============================================================================
CREATE OR REPLACE FILE FORMAT SNOW_FASHION.RAW.CSV_GZ_FORMAT
  TYPE                      = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER               = 1
  COMPRESSION               = GZIP
  EMPTY_FIELD_AS_NULL       = TRUE
  NULL_IF                   = ('NULL', '');

-- =============================================================================
-- 2. Internal Stage
-- =============================================================================
CREATE OR REPLACE STAGE SNOW_FASHION.RAW.LOAD_STAGE
  FILE_FORMAT = CSV_GZ_FORMAT;

-- =============================================================================
-- 3. 파일 업로드 (PUT)
-- 아래 경로를 실제 CSV 파일이 있는 로컬 경로로 변경하세요.
-- Snowsight UI에서는 각 테이블 → Load Data 로 직접 업로드할 수도 있습니다.
-- =============================================================================

-- 방법 A: SnowSQL / Snowflake CLI 에서 실행
-- PUT file:///path/to/data/*.csv.gz @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE;

-- 방법 B: 개별 파일 PUT (경로를 본인 환경에 맞게 수정)
PUT file:///path/to/data/CUSTOMERS.csv.gz          @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/DEMAND_FORECAST.csv.gz    @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/INVENTORY_SNAPSHOT.csv.gz  @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/PRODUCTS.csv.gz           @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/PRODUCT_REVIEWS.csv.gz    @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/REVIEW_TEMPLATES.csv.gz   @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/SALES_TRANSACTIONS.csv.gz @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/SHIPMENTS.csv.gz          @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/STORES.csv.gz             @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/SUPPLY_ORDERS.csv.gz      @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/VENDORS.csv.gz            @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file:///path/to/data/WEEKLY_DEMAND.csv.gz      @SNOW_FASHION.RAW.LOAD_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- 업로드 확인
LIST @SNOW_FASHION.RAW.LOAD_STAGE;

-- =============================================================================
-- 4. 데이터 로드 (COPY INTO)
-- =============================================================================

COPY INTO SNOW_FASHION.RAW.CUSTOMERS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/CUSTOMERS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.DEMAND_FORECAST
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/DEMAND_FORECAST.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.INVENTORY_SNAPSHOT
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/INVENTORY_SNAPSHOT.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.PRODUCTS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/PRODUCTS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.PRODUCT_REVIEWS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/PRODUCT_REVIEWS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.REVIEW_TEMPLATES
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/REVIEW_TEMPLATES.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.SALES_TRANSACTIONS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/SALES_TRANSACTIONS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.SHIPMENTS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/SHIPMENTS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.STORES
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/STORES.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.SUPPLY_ORDERS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/SUPPLY_ORDERS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.VENDORS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/VENDORS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.WEEKLY_DEMAND
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/WEEKLY_DEMAND.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- 5. 데이터 확인
-- =============================================================================
SELECT 'CUSTOMERS' AS TBL, COUNT(*) AS CNT FROM SNOW_FASHION.RAW.CUSTOMERS
UNION ALL SELECT 'DEMAND_FORECAST', COUNT(*) FROM SNOW_FASHION.RAW.DEMAND_FORECAST
UNION ALL SELECT 'INVENTORY_SNAPSHOT', COUNT(*) FROM SNOW_FASHION.RAW.INVENTORY_SNAPSHOT
UNION ALL SELECT 'PRODUCTS', COUNT(*) FROM SNOW_FASHION.RAW.PRODUCTS
UNION ALL SELECT 'PRODUCT_REVIEWS', COUNT(*) FROM SNOW_FASHION.RAW.PRODUCT_REVIEWS
UNION ALL SELECT 'REVIEW_TEMPLATES', COUNT(*) FROM SNOW_FASHION.RAW.REVIEW_TEMPLATES
UNION ALL SELECT 'SALES_TRANSACTIONS', COUNT(*) FROM SNOW_FASHION.RAW.SALES_TRANSACTIONS
UNION ALL SELECT 'SHIPMENTS', COUNT(*) FROM SNOW_FASHION.RAW.SHIPMENTS
UNION ALL SELECT 'STORES', COUNT(*) FROM SNOW_FASHION.RAW.STORES
UNION ALL SELECT 'SUPPLY_ORDERS', COUNT(*) FROM SNOW_FASHION.RAW.SUPPLY_ORDERS
UNION ALL SELECT 'VENDORS', COUNT(*) FROM SNOW_FASHION.RAW.VENDORS
UNION ALL SELECT 'WEEKLY_DEMAND', COUNT(*) FROM SNOW_FASHION.RAW.WEEKLY_DEMAND
ORDER BY TBL;
