-- =============================================================================
-- Snow Fashion 데이터 적재 스크립트
-- 사전 조건: 00_setup_db.sql 실행 완료, LOAD_STAGE에 .csv.gz 파일 12개 업로드 완료
-- 실행 환경: Snowsight 워크시트
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SF_WH;
USE SCHEMA SNOW_FASHION.RAW;

-- =============================================================================
-- 1. 스테이지 파일 확인 (12개 파일이 보여야 합니다)
-- =============================================================================
LIST @SNOW_FASHION.RAW.LOAD_STAGE;

-- =============================================================================
-- 2. 데이터 적재 (COPY INTO)
-- =============================================================================

COPY INTO SNOW_FASHION.RAW.CUSTOMERS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/CUSTOMERS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.DEMAND_FORECAST
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/DEMAND_FORECAST.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.INVENTORY_SNAPSHOT
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/INVENTORY_SNAPSHOT.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.PRODUCTS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/PRODUCTS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.PRODUCT_REVIEWS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/PRODUCT_REVIEWS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.REVIEW_TEMPLATES
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/REVIEW_TEMPLATES.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.SALES_TRANSACTIONS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/SALES_TRANSACTIONS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.SHIPMENTS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/SHIPMENTS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.STORES
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/STORES.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.SUPPLY_ORDERS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/SUPPLY_ORDERS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.VENDORS
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/VENDORS.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

COPY INTO SNOW_FASHION.RAW.WEEKLY_DEMAND
  FROM @SNOW_FASHION.RAW.LOAD_STAGE/WEEKLY_DEMAND.csv.gz
  FILE_FORMAT = CSV_GZ_FORMAT
  ON_ERROR = 'CONTINUE';

-- =============================================================================
-- 3. 데이터 확인
-- =============================================================================
SELECT 'CUSTOMERS' AS TBL, COUNT(*) AS CNT FROM SNOW_FASHION.RAW.CUSTOMERS
UNION ALL SELECT 'DEMAND_FORECAST', COUNT(*) FROM SNOW_FASHION.RAW.DEMAND_FORECAST
UNION ALL SELECT 'INVENTORY_SNAPSHOT', COUNT(*) FROM SNOW_FASHION.RAW.INVENTORY_SNAPSHOT
UNION ALL SELECT 'PRODUCTS', COUNT(*) FROM SNOW_FASHION.RAW.PRODUCTS
UNION ALL SELECT 'PRODUCT_REVIEWS', COUNT(*) FROM SNOW_FASHION.RAW.PRODUCT_REVIEWS
UNION ALL SELECT 'REVIEW_TEMPLATES', COUNT(*) FROM SNOW_FASHION.RAW.REVIEW_TEMPLATES
UNION ALL SELECT 'SALES_TRANSACTIONS', COUNT(*) FROM SNOW_FASHION.RAW.SALES_TRANSACTIONS
UNION ALL SELECT 'SHIPMENTS', COUNT(*) FROM SNOW_FASHION.RAW.SHIPMENTS
UNION ALL SELECT 'STORES', COUNT(*) FROM SNOW_FASHION.RAW.STORES
UNION ALL SELECT 'SUPPLY_ORDERS', COUNT(*) FROM SNOW_FASHION.RAW.SUPPLY_ORDERS
UNION ALL SELECT 'VENDORS', COUNT(*) FROM SNOW_FASHION.RAW.VENDORS
UNION ALL SELECT 'WEEKLY_DEMAND', COUNT(*) FROM SNOW_FASHION.RAW.WEEKLY_DEMAND
ORDER BY TBL;
